openapi: 3.0.3
info:
  contact:
    email: sg5@afnor.org
    name: AFNOR
  description: "The __Flow Service API__ allows to:\n  - Upload a flow.\n  - Retrieve\
    \ information related to a set of flows.\n  - Download a flow given its identifier\n\
    \nThe resources of the API are :\n  - `/flows` : with creation and retrieval methods.\n\
    \  - `/flows/webhooks` : creation, update, delete, list\n\nWorflow example:\n\
    \  - `POST /flows` : provide the flow information & content\n  - `POST /flows/search`\
    \ : retrieve flows given multiple criterias.\n  - `GET /flows/{id}` : download\
    \ a flow based on its id.\n  - `POST /flows/webhooks` : subscribe to a channel\
    \ of event\n \nHistory:\n  - `1.0.0` : First release\n  - `1.0.1` : Fixes following\
    \ 2025/04/15 SG5 plenary meeting\n    - Remove AcknowledgementXXX enumerates from\
    \ FlowType\n    - Acknowledgement is now based upon details (level, item, reason)\n\
    \    - Add the attachment number in the flow information\n    - Add query parameters\
    \ docType & docIndex to aim a specific download\n    - Change pagination method,\
    \ from cursors to offsets\n  - `1.0.2` : Fixes following 2025/05/06 SG5 plenary\
    \ meeting\n    - FlowId & TrackingId as not only UUID for more flexibility\n \
    \   - Add sha256 fingerprint to allow integrity check\n    - Add trackingId as\
    \ a filter criteria and in the Flow object\n    - Add full FlowInfo object + submission\
    \ date in POST response\n    - Add comments\n  - `1.1.0` : Fixes following 2025/05/20\
    \ SG5 meeting\n    - Get operation: allows also to return the flow data when docType\
    \ is set to Metadata\n    - Search operation: flowId is no longer a criteria,\
    \ prefer too use the Get by Id operation\n    - Remove any reference to any attached\
    \ document to the flow\n    - Refactor FullFlowInfo schema\n    - FlowType update\
    \ (FRR 10.*) for reporting\n    - AcknowledgementDetail update to add a message\
    \ and a code\n    - offset removal, do pagination using updatedAfter\n    - remove\
    \ 206 status code\n    - Add StateInvoice & associated LC in FlowType enum\n \
    \   - Add extensible reason codes related to Life cycle errors\n    - Add ProcessingRule\
    \ to the flow object & criteria\n    - Add webhooks callback contents\n  - `1.2.0`\
    \ : \n    - Webhook management, create, update, list, delete, get\n    - Add new\
    \ flow types: B2G, B2GInt, B2GOutOfScope\n    - Add new client credentials OAuth2\
    \ workflow\n    - Optimized FlowInfo/FullFlowInfo/Flow schemas\n    - Add name\
    \ in Flow schema\n    - Add OAuth2 securityScheme\n    - Add Header parameter\
    \ Organization-Id to ease delegation\n  - `1.3.0` :\n    - Increase NotOnlyUuid\
    \ to 64 characters\n    - Update Webhook configuration:\n      - remove processingRule\
    \ from Metadata\n      - remove any required metadata field (metadat can be empty)\n\
    \      - simplify configuration (remove headers, auth & signature block)\n   \
    \   - enrich URL path flexibility\n    - Added missing required for : processingRule\
    \ & flowProfile in Flow schema in responses\n    - Add base path and service name\
    \ as variables in server URL\n    - Remove StateInvoice flow type\n    - Add new\
    \ flowtypes related to e-reporting flows sent to DFH\n      - StateCustomerInvoice\n\
    \      - StateSupplierInvoice\n      - StateTransactionReport\n      - StateTransactionReportLC\n\
    \      - StatePaymentReport\n      - StatePaymentReportLC\n    - Use a cursor-based\
    \ pagination, more efficient than using just dates\n      - cursor in request\n\
    \      - nextCursor in response\n    - Add Undefined values for ProfileType, FlowType\
    \ & ProcessingRule\n      - These 3 properties may not be defined in Pending &\
    \ Error states\n"
  title: AFNOR Flow Service
  version: 1.3.0
servers:
- description: Prod public URLs
  url: "https://{sub-domain}.{domain}{base-path}/{service-name}"
  variables:
    sub-domain:
      default: api.flow
      description: Sub domain related to the Flow API if any
    domain:
      default: company.com
      description: Domain name
    base-path:
      default: ""
      description: "Custom path that may be used for routing, customer, PA, API"
    service-name:
      default: flow-service
      description: If service name is not the default one
security:
- BearerAuth: []
- OAuth2: []
tags:
- description: Flow management
  name: Flow
- description: Service supervision
  name: Supervisor
- description: Webhook management
  name: Webhook
paths:
  /v1/flows:
    post:
      description: "Submit a flow. A flow is a single-invoice file, with :\n  - an\
        \ XML/PDF file with the data of the invoice\n\nThe flow is created with a\
        \ `flowInfo` object, allowing to qualify the flow.\n  \nA flow can be :\n\
        \  - an invoice (CII, UBL, Factur-X,...) \n  - a lifecycle (CDAR) \n  - or\
        \ a e-reporting file\n"
      operationId: createFlow
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/FlowPostRequest'
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullFlowInfo'
          description: |
            OK - Response message once the flow has been uploaded.
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "413":
          content:
            application/json:
              example:
                errorCode: FILE_SIZE_EXCEEDED
                errorMessage: Provided file is too big
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 413 : Payload Too Large."
        "422":
          content:
            application/json:
              example:
                errorCode: UNPROCESSABLE_ENTITY
                errorMessage: Entity consistency error
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 422 : Unprocessable entity."
        "429":
          content:
            application/json:
              example:
                errorCode: TOO_MANY_REQUESTS
                errorMessage: The client emitted too many requests
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 429 : Too many requests."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Submit a new flow
      tags:
      - Flow
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
  /v1/flows/search:
    post:
      description: |
        Retrieves a set of flows matching the provided search criteria:
          - Need at least one criterion to be specified
          - Assuming a logical AND when combining criteria
          - Assuming a logical OR for criteria allowing a list of values

        Pagination works with 2 different ways:
          - with dates and the updatedAfter property
            - the comparison with current date is strict : updatedAt > updatedAfter
          - with cursors (more secure)
            - in case of pagination a nextCursor will be returned
            - next pagination call shall set cursor value to nextCursor value of last call
      operationId: searchFlows
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/FlowSearchRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFlowContent'
          description: |
            OK - Response message when returning the results of a search request.
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "429":
          content:
            application/json:
              example:
                errorCode: TOO_MANY_REQUESTS
                errorMessage: The client emitted too many requests
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 429 : Too many requests."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Select flows upon criteria
      tags:
      - Flow
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/flows/{flowId}:
    get:
      description: |
        Download a file related to a given flow:
          - an invoice
          - a life cycle
          - an e-reporting
      operationId: getFlow
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      - description: Flow identifier
        explode: false
        in: path
        name: flowId
        required: true
        schema:
          $ref: '#/components/schemas/NotOnlyUuid'
        style: simple
      - description: |
          This parameter allows to provide the type of file to be downloaded, can be either one:
            - Metadata [Default]: provides the flow metadata as a JSON payload, no download
            - Original: the document that has been initially sent/provided by the emitter
            - Converted: the document that has been optionally converted by the system
            - ReadableView: the document that has been optionally generated as the readable file
        explode: true
        in: query
        name: docType
        required: false
        schema:
          default: Metadata
          enum:
          - Metadata
          - Original
          - Converted
          - ReadableView
          type: string
        style: form
      responses:
        "200":
          content:
            application/octet-stream: {}
            application/json:
              schema:
                $ref: '#/components/schemas/Flow'
          description: OK - Response message once the flow has been downloaded.
          headers:
            Content-Disposition:
              description: Header specifying attached file name
              explode: false
              schema:
                pattern: attachment;filename=*
                type: string
              style: simple
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "404":
          content:
            application/json:
              example:
                errorCode: MISSING_RESOURCE
                errorMessage: Requested resource is Not Found
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 404 : Resource Not Found."
        "429":
          content:
            application/json:
              example:
                errorCode: TOO_MANY_REQUESTS
                errorMessage: The client emitted too many requests
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 429 : Too many requests."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Download the file of a flow
      tags:
      - Flow
      x-accepts:
      - application/json
      - application/octet-stream
  /v1/webhooks:
    get:
      operationId: listWebhooks
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listWebhooks_200_response'
          description: OK - Webhook List Response
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Retrieve the list of webhooks created by the owner of the token
      tags:
      - Webhook
      x-accepts:
      - application/json
    post:
      callbacks:
        WebhookCallback:
          $ref: '#/components/callbacks/WebhookCallback'
      description: "This operation creates and configures a new webhook, providing:\n\
        - The callback URL\n- The metadata to filter on subsets of events\n\nThe webhook\
        \ belongs to the owner of the token and cannot be seen from others:\n- It\
        \ returns an id and a signing key (256 or 512 bits) that should be kept\n\
        - The signing key allows to validate the signature of each received event.\n\
        \nHow the signature is managed:\n- At webhook creation a signing Key is randomly\
        \ generated in a secure way\n  - 256 bits are enough if the random generator\
        \ is secure \n  - 512 bits are necessary if the generator is not secure\n\
        - Each time an event is sent:\n  - a SHA-256 fingerprint is generated based\
        \ on the concatenation of:\n    - the JSON payload of the response (as is,\
        \ no canonical format)\n    - a separator : @\n    - the current epoch time\
        \ in seconds\n  - a HMAC signature is computed over the fingerprint with the\
        \ callback signing key\n  - the signature is base64 encoded for the transport\n\
        \  \nThe signature and the timestamp are returned in the following headers\
        \ of the callback:\n  - Afnor-Signature is the signature (base64)\n  - Afnor-Signature-Timestamp\
        \ is the epoch timestamp in seconds\n"
      operationId: createWebhook
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/WebhookPostRequest'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookIdParam'
          description: OK - Webhook Created
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Subscribe to a webhook
      tags:
      - Webhook
      x-content-type: application/json
      x-accepts:
      - application/json
  /v1/webhooks/{webhookUid}:
    delete:
      description: |
        - Delete a subscription owned by the owner of the token
        - The operation is allowed only buy the owner of the token
      operationId: deleteWebhook
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The webhook unique ID
        explode: false
        in: path
        name: webhookUid
        required: true
        schema:
          $ref: '#/components/schemas/WebhookId'
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content - No content expected
        "400":
          content:
            application/json:
              example:
                errorCode: MISSING_REQUIRED_FIELD
                errorMessage: Invalid request format
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 400 : Bad request."
        "401":
          content:
            application/json:
              example:
                errorCode: MISSING_TOKEN
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 401 : Authentication error."
        "403":
          content:
            application/json:
              example:
                errorCode: FORBIDDEN_ACCESS
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 403 : Forbidden."
        "404":
          content:
            application/json:
              example:
                errorCode: MISSING_RESOURCE
                errorMessage: Requested resource is Not Found
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 404 : Resource Not Found."
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Unsubscribe to a webhook
      tags:
      - Webhook
      x-accepts:
      - application/json
  /v1/healthcheck:
    get:
      operationId: getHealth
      parameters:
      - description: Header parameter used to correlate logs from several components
        explode: false
        in: header
        name: Request-Id
        required: false
        schema:
          format: uuid
          type: string
        style: simple
      - description: The organization that is aimed in a multi tenancy context
        explode: false
        in: header
        name: Organization-Id
        required: false
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: OK - Operation succeeded
        "500":
          content:
            application/json:
              example:
                errorCode: INTERNAL_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 500 : Server Internal Error."
        "503":
          content:
            application/json:
              example:
                errorCode: RESOURCE_ERROR
                errorMessage: null
              schema:
                $ref: '#/components/schemas/Error'
          description: "Error 503 : Unavailable Resource."
      summary: Check whether the API service is up and running.
      tags:
      - Supervisor
      x-accepts:
      - application/json
components:
  callbacks:
    WebhookCallback:
      '{$request.body#/callback.url}':
        post:
          parameters:
          - description: |
              The HMAC-SHA-256 signature payload
            explode: false
            in: header
            name: Afnor-Signature
            required: false
            schema:
              description: Base 64 encoded string
              format: byte
              type: string
            style: simple
          - description: "The timestamp is an epoch time in seconds \nEncoded as a\
              \ 64 bit integer to avoid the limitation reached in 2038\n"
            explode: false
            in: header
            name: Afnor-Signature-Timestamp
            required: true
            schema:
              format: int64
              type: integer
            style: simple
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Flow'
            required: true
          responses:
            "200":
              description: OK - Operation succeeded
            "400":
              content:
                application/json:
                  example:
                    errorCode: MISSING_REQUIRED_FIELD
                    errorMessage: Invalid request format
                  schema:
                    $ref: '#/components/schemas/Error'
              description: "Error 400 : Bad request."
            "401":
              content:
                application/json:
                  example:
                    errorCode: MISSING_TOKEN
                    errorMessage: null
                  schema:
                    $ref: '#/components/schemas/Error'
              description: "Error 401 : Authentication error."
            "403":
              content:
                application/json:
                  example:
                    errorCode: FORBIDDEN_ACCESS
                    errorMessage: null
                  schema:
                    $ref: '#/components/schemas/Error'
              description: "Error 403 : Forbidden."
            "500":
              content:
                application/json:
                  example:
                    errorCode: INTERNAL_ERROR
                    errorMessage: null
                  schema:
                    $ref: '#/components/schemas/Error'
              description: "Error 500 : Server Internal Error."
  parameters:
    WebhookUidPathParam:
      description: The webhook unique ID
      explode: false
      in: path
      name: webhookUid
      required: true
      schema:
        $ref: '#/components/schemas/WebhookId'
      style: simple
    OrganizationIdHeaderParam:
      description: The organization that is aimed in a multi tenancy context
      explode: false
      in: header
      name: Organization-Id
      required: false
      schema:
        type: string
      style: simple
    RequestIdHeader:
      description: Header parameter used to correlate logs from several components
      explode: false
      in: header
      name: Request-Id
      required: false
      schema:
        format: uuid
        type: string
      style: simple
  requestBodies:
    FlowSearchRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchFlowParams'
    FlowPostRequest:
      content:
        multipart/form-data:
          encoding:
            file:
              contentType: "application/pdf, application/xml"
              style: form
            flowInfo:
              contentType: application/json
              style: form
          schema:
            $ref: '#/components/schemas/createFlow_request'
    WebhookPostRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebhookParams'
      description: Create a webhook
  responses:
    FlowSearchResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SearchFlowContent'
      description: |
        OK - Response message when returning the results of a search request.
    FlowPostResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FullFlowInfo'
      description: |
        OK - Response message once the flow has been uploaded.
    FlowGetResponse:
      content:
        application/octet-stream: {}
        application/json:
          schema:
            $ref: '#/components/schemas/Flow'
      description: OK - Response message once the flow has been downloaded.
      headers:
        Content-Disposition:
          description: Header specifying attached file name
          explode: false
          schema:
            pattern: attachment;filename=*
            type: string
          style: simple
    WebhookLightResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WebhookIdParam'
      description: OK - Webhook Created
    WebhookListResponse:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/listWebhooks_200_response'
      description: OK - Webhook List Response
    Error400Response:
      content:
        application/json:
          example:
            errorCode: MISSING_REQUIRED_FIELD
            errorMessage: Invalid request format
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 400 : Bad request."
    Error401Response:
      content:
        application/json:
          example:
            errorCode: MISSING_TOKEN
            errorMessage: null
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 401 : Authentication error."
    Error403Response:
      content:
        application/json:
          example:
            errorCode: FORBIDDEN_ACCESS
            errorMessage: null
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 403 : Forbidden."
    Error413Response:
      content:
        application/json:
          example:
            errorCode: FILE_SIZE_EXCEEDED
            errorMessage: Provided file is too big
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 413 : Payload Too Large."
    Error422Response:
      content:
        application/json:
          example:
            errorCode: UNPROCESSABLE_ENTITY
            errorMessage: Entity consistency error
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 422 : Unprocessable entity."
    Error429Response:
      content:
        application/json:
          example:
            errorCode: TOO_MANY_REQUESTS
            errorMessage: The client emitted too many requests
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 429 : Too many requests."
    Error500Response:
      content:
        application/json:
          example:
            errorCode: INTERNAL_ERROR
            errorMessage: null
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 500 : Server Internal Error."
    Error503Response:
      content:
        application/json:
          example:
            errorCode: RESOURCE_ERROR
            errorMessage: null
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 503 : Unavailable Resource."
    Error404Response:
      content:
        application/json:
          example:
            errorCode: MISSING_RESOURCE
            errorMessage: Requested resource is Not Found
          schema:
            $ref: '#/components/schemas/Error'
      description: "Error 404 : Resource Not Found."
    Ok204EmptyResponse:
      description: No Content - No content expected
    Ok200EmptyResponse:
      description: OK - Operation succeeded
  schemas:
    NotOnlyUuid:
      description: "Unique identifier supporting UUID but not only, for flexibility\
        \ purpose"
      maxLength: 64
      type: string
    Cursor:
      description: "Pagination, Opaque cursor for pagination management, acts as a\
        \ bookmark"
      example: eyJjcmVhdGVkX2F0IjoiMjAyNS0wNi0wOVQxMDowMDowMFoiLCJpZCI6MTIzNH0=
      type: string
    Limit:
      default: 25
      description: "Pagination, Maximum number of results that may be returned"
      maximum: 100
      type: integer
    ProcessingRule:
      description: |
        - B2B                 : e-invoicing
        - B2BInt              : International B2B e-reporting
        - B2C                 : B2C e-reporting
        - B2G                 : e-invoicing for B2G sales
        - B2GInt
        - OutOfScope          : Out of scope (not regulated flow)
        - B2GOutOfScope
        - ArchiveOnly         : Archive only, no transmission
        - NotApplicable       : Not Applicable
        - Undefined           : Not yet defined when in Pending state or unable to define when in Error state
      enum:
      - B2B
      - B2BInt
      - B2C
      - B2G
      - B2GInt
      - OutOfScope
      - B2GOutOfScope
      - ArchiveOnly
      - NotApplicable
      - Undefined
      type: string
    FlowSyntax:
      description: Syntax of the original file belonging to a flow
      enum:
      - CII
      - UBL
      - Factur-X
      - CDAR
      - FRR
      example: CII
      type: string
    FlowProfile:
      enum:
      - Basic
      - CIUS
      - Extended-CTC-FR
      - Undefined
      type: string
    FlowType:
      description: |
        - `CustomerInvoice`: a non-self-billed outgoing invoice or a self-billed incoming invoice
        - `SupplierInvoice`: a non-self-billed incoming invoice or self-billed outgoing invoice
        - `CustomerInvoiceLC`: a lifecycle (CDAR) related to a customer invoice
        - `SupplierInvoiceLC`: a lifecycle (CDAR) related to supplier invoice
        - `StateCustomerInvoiceLC`: a customer invoice LC sent to DFH
        - `StateSupplierInvoiceLC`: a supplier invoice LC sent to DFH
        - `AggregatedCustomerTransactionReport` : a transaction e-reporting flow containing aggregated B2C sales (FRR 10.3)
        - `UnitaryCustomerTransactionReport`: a transaction e-reporting flow containing international B2B sales or a B2C transaction flow reported individually (FRR 10.1)
        - `AggregatedCustomerPaymentReport` : an e-reporting of collections flow containing collections linked to B2C sales (FRR 10.4)
        - `UnitaryCustomerPaymentReport` : an e-reporting of collections flow containing collections linked to unit international B2B sales or B2C sales (FRR 10.2)
        - `UnitarySupplierTransactionReport`: a transaction e-reporting flow containing international B2B purchases (FRR 10.1)
        - `MultiFlowReport`: an e-reporting flow which contains at least 2 different flow types (FRR 10)
        - `StateCustomerInvoice` : a reporting flow 1 sent to DFH related to an invoice of type ‘CustomerInvoice’
        - `StateSupplierInvoice` : a reporting flow 1 sent to DFH related to an invoice of type ‘SupplierInvoice’ for self-billing
        - `StateTransactionReport` : a transaction e-reporting flow 10.1 or 10.3 sent to the DFH
        - `StateTransactionReportLC` : a lifecycle for a StateTransactionReport flow
        - `StatePaymentReport` : a payment e-reporting flow 10.2 or 10.4 sent to DFH
        - `StatePaymentReportLC` : a lifecycle for a StatePaymentReport flow
        - `Undefined`            : Not yet defined when in Pending state or unable to define when in Error state
      enum:
      - CustomerInvoice
      - SupplierInvoice
      - CustomerInvoiceLC
      - SupplierInvoiceLC
      - StateCustomerInvoiceLC
      - StateSupplierInvoiceLC
      - AggregatedCustomerTransactionReport
      - UnitaryCustomerTransactionReport
      - AggregatedCustomerPaymentReport
      - UnitaryCustomerPaymentReport
      - UnitarySupplierTransactionReport
      - MultiFlowReport
      - StateCustomerInvoice
      - StateSupplierInvoice
      - StateTransactionReport
      - StateTransactionReportLC
      - StatePaymentReport
      - StatePaymentReportLC
      - Undefined
      example: SupplierInvoice
      type: string
    FlowDirection:
      description: |
        Direction of the flow:
          - `In`:  Incoming flow, from the PDP to the OD
          - `Out`: Outgoing flow, from the OD to the PDP
      enum:
      - In
      - Out
      example: Out
      type: string
    FlowAckStatus:
      description: |
        - `Ok`: the following checks have passed:
          - Anti virus
          - Integrity checks
          - Technical rules checks
          - Unicity checks
        - `Error`: one of the previous test has failed
        - `Pending` : the flow is not yet integrated
      enum:
      - Pending
      - Ok
      - Error
      type: string
    ReasonCode:
      description: A predefined set of reason code values + ability to extend this
        set
      type: string
    ReasonCodeEnum:
      description: |
        - `EmptyAttachement`      : One or more attachments are empty. (ie IRR_VID_PJ)
        - `AttachmentTypeError`   : The type and/or extension of one or more attachments is not compliant. (ie IRR_EXT_DOC)
        - `EmptyFlow`             : The binary flow is empty. (ie IRR_VID_F)
        - `OtherTechnicalError`   : Other technical error. (ie AUTRE)
        - `InvalidSchema`         : Invalid XML schema. (ie IRR_SYNTAX)
        - `FileSizeExceeded`      : File size limit reached. (ie IRR_TAILLE_F)
        - `FlowTypeError`         : The flow type and/or extension are not compliant. (ie IRR_TYPE_F)
        - `AlreadyExistingFlow`   : The flow has already been sent and received. (ie N/A)
        - `VirusFound`            : Presence of a virus. (ie IRR_ANTIVIRUS)
        - `ChecksumMismatch`      : Checksum provided is different from computed one
        - `InvoiceLCInvalidStatus`: One or more statuses are inconsistent
        - `InvoiceLCStatusError`  : One or more statuses are incorrect or not allowed
        - `InvoiceLCRuleError`    : One or more rules are not matched
        - `InvoiceLCAccessDenied` : One of the request is not authorized and requests permissions
        - `InvoiceLCAmountError`  : One or more amounts are not consistent in regards to the VAT
      enum:
      - EmptyAttachement
      - AttachmentTypeError
      - EmptyFlow
      - OtherTechnicalError
      - InvalidSchema
      - FileSizeExceeded
      - FlowTypeError
      - AlreadyExistingFlow
      - VirusFound
      - ChecksumMismatch
      - InvoiceLCInvalidStatus
      - InvoiceLCStatusError
      - InvoiceLCRuleError
      - InvoiceLCAccessDenied
      - InvoiceLCAmountError
      type: string
    CoreFlowInfo:
      description: "Core schema to build FlowInfo, FullFlowInfo, Flow schemas"
      properties:
        trackingId:
          allOf:
          - $ref: '#/components/schemas/NotOnlyUuid'
          description: The tracking id is an external identifier and is used to track
            the flow by the sender
        name:
          description: Name of the file
          maxLength: 255
          type: string
        processingRule:
          $ref: '#/components/schemas/ProcessingRule'
        flowSyntax:
          $ref: '#/components/schemas/FlowSyntax'
        flowProfile:
          $ref: '#/components/schemas/FlowProfile'
      required:
      - flowSyntax
      - name
      type: object
    FlowInfoExtension:
      description: Extension to build the FlowInfo
      properties:
        sha256:
          description: |
            The sha256 is the fingerprint of the attached file:
            - if provided in the request: it should be checked once received
            - if not provided in the request: it may be computed and returned in the response
          format: byte
          pattern: "^[a-f0-9]{64}$"
          type: string
      type: object
    FlowInfo:
      allOf:
      - $ref: '#/components/schemas/CoreFlowInfo'
      - $ref: '#/components/schemas/FlowInfoExtension'
      description: Signaling of the flow
    SearchFlowParams:
      example:
        cursor: ""
        limit: 8
        where:
          updatedBefore: 2000-01-23T04:56:07.000+00:00
          updatedAfter: 2000-01-23T04:56:07.000+00:00
          processingRule:
          - B2B
          - B2B
          flowDirection:
          - Out
          - Out
          ackStatus: Pending
          flowType:
          - SupplierInvoice
          - SupplierInvoice
          trackingId: trackingId
      properties:
        limit:
          default: 25
          description: "Pagination, Maximum number of results that may be returned"
          maximum: 100
          type: integer
        cursor:
          allOf:
          - $ref: '#/components/schemas/Cursor'
          description: "If cursor is provided, then start search starting from that\
            \ cursor"
        where:
          $ref: '#/components/schemas/SearchFlowFilters'
      required:
      - where
      type: object
    SearchFlowFilters:
      description: "Filtering criteria, at least one is required"
      example:
        updatedBefore: 2000-01-23T04:56:07.000+00:00
        updatedAfter: 2000-01-23T04:56:07.000+00:00
        processingRule:
        - B2B
        - B2B
        flowDirection:
        - Out
        - Out
        ackStatus: Pending
        flowType:
        - SupplierInvoice
        - SupplierInvoice
        trackingId: trackingId
      properties:
        updatedAfter:
          description: "The comparison with current date is strict : updatedAt > updatedAfter"
          format: date-time
          type: string
        updatedBefore:
          format: date-time
          type: string
        processingRule:
          items:
            $ref: '#/components/schemas/ProcessingRule'
          type: array
        flowType:
          items:
            $ref: '#/components/schemas/FlowType'
          type: array
        flowDirection:
          items:
            $ref: '#/components/schemas/FlowDirection'
          type: array
        trackingId:
          description: "Unique identifier supporting UUID but not only, for flexibility\
            \ purpose"
          maxLength: 64
          type: string
        ackStatus:
          $ref: '#/components/schemas/FlowAckStatus'
      type: object
    FullFlowInfoExtension:
      description: "Extension schema to build FullFlowInfo, Flow schemas"
      properties:
        flowId:
          description: "Unique identifier supporting UUID but not only, for flexibility\
            \ purpose"
          maxLength: 64
          type: string
        submittedAt:
          description: |
            The flow submission date and time (the date and time when the flow was created on the system)
            This property should be used by the API consumer as a time reference to avoid clock synchronization issues
          format: date-time
          type: string
      required:
      - flowId
      - submittedAt
      type: object
    FullFlowInfo:
      allOf:
      - $ref: '#/components/schemas/FullFlowInfoExtension'
      - $ref: '#/components/schemas/FlowInfo'
      description: "Identified Flow info: flow info + id + timestamp"
      example:
        flowProfile: Basic
        processingRule: B2B
        sha256: sha256
        name: name
        flowSyntax: CII
        submittedAt: 2000-01-23T04:56:07.000+00:00
        flowId: flowId
        trackingId: ""
    AcknowledgementDetail:
      example:
        item: item
        level: Error
        reasonMessage: reasonMessage
        reasonCode: reasonCode
      properties:
        level:
          enum:
          - Error
          - Warning
          type: string
        item:
          description: Item on which the error refers
          type: string
        reasonCode:
          description: A predefined set of reason code values + ability to extend
            this set
          type: string
        reasonMessage:
          type: string
      required:
      - item
      - level
      - reasonCode
      - reasonMessage
      type: object
    AcknowledgementDetails:
      items:
        $ref: '#/components/schemas/AcknowledgementDetail'
      minItems: 1
      type: array
    Acknowledgement:
      example:
        details:
        - item: item
          level: Error
          reasonMessage: reasonMessage
          reasonCode: reasonCode
        - item: item
          level: Error
          reasonMessage: reasonMessage
          reasonCode: reasonCode
        status: null
      properties:
        status:
          $ref: '#/components/schemas/FlowAckStatus'
        details:
          items:
            $ref: '#/components/schemas/AcknowledgementDetail'
          minItems: 1
          type: array
      required:
      - status
      type: object
    FlowExtension:
      description: Extension schema to build Flow schema
      properties:
        updatedAt:
          description: |
            The last update date and time of the flow. When the flow is submitted updatedAt is equal to submittedAt.
            When the flow acknowledgment status is changed updatedAt date and time is updated.
          format: date-time
          type: string
        flowType:
          $ref: '#/components/schemas/FlowType'
        processingRuleSource:
          description: Says whether the processing rule has been computed or the processing
            rule was an input parameter
          enum:
          - Input
          - Computed
          type: string
        flowDirection:
          $ref: '#/components/schemas/FlowDirection'
        acknowledgement:
          $ref: '#/components/schemas/Acknowledgement'
      required:
      - acknowledgement
      - flowDirection
      - flowType
      - processingRuleSource
      - updatedAt
      type: object
    Flow:
      allOf:
      - $ref: '#/components/schemas/CoreFlowInfo'
      - $ref: '#/components/schemas/FullFlowInfoExtension'
      - $ref: '#/components/schemas/FlowExtension'
      description: The properties of a Flow resource
      example:
        flowProfile: Basic
        processingRuleSource: Input
        processingRule: null
        acknowledgement:
          details:
          - item: item
            level: Error
            reasonMessage: reasonMessage
            reasonCode: reasonCode
          - item: item
            level: Error
            reasonMessage: reasonMessage
            reasonCode: reasonCode
          status: null
        flowDirection: Out
        name: name
        flowSyntax: CII
        submittedAt: 2000-01-23T04:56:07.000+00:00
        flowId: flowId
        trackingId: ""
        updatedAt: 2000-01-23T04:56:07.000+00:00
        flowType: SupplierInvoice
      required:
      - flowProfile
      - processingRule
    SearchFlowContent:
      description: "A set of flows matching criterias, provided into the request"
      example:
        nextCursor: ""
        limit: 8
        filters:
          updatedBefore: 2000-01-23T04:56:07.000+00:00
          updatedAfter: 2000-01-23T04:56:07.000+00:00
          processingRule:
          - B2B
          - B2B
          flowDirection:
          - Out
          - Out
          ackStatus: Pending
          flowType:
          - SupplierInvoice
          - SupplierInvoice
          trackingId: trackingId
        results:
        - flowProfile: Basic
          processingRuleSource: Input
          processingRule: null
          acknowledgement:
            details:
            - item: item
              level: Error
              reasonMessage: reasonMessage
              reasonCode: reasonCode
            - item: item
              level: Error
              reasonMessage: reasonMessage
              reasonCode: reasonCode
            status: null
          flowDirection: Out
          name: name
          flowSyntax: CII
          submittedAt: 2000-01-23T04:56:07.000+00:00
          flowId: flowId
          trackingId: ""
          updatedAt: 2000-01-23T04:56:07.000+00:00
          flowType: SupplierInvoice
        - flowProfile: Basic
          processingRuleSource: Input
          processingRule: null
          acknowledgement:
            details:
            - item: item
              level: Error
              reasonMessage: reasonMessage
              reasonCode: reasonCode
            - item: item
              level: Error
              reasonMessage: reasonMessage
              reasonCode: reasonCode
            status: null
          flowDirection: Out
          name: name
          flowSyntax: CII
          submittedAt: 2000-01-23T04:56:07.000+00:00
          flowId: flowId
          trackingId: ""
          updatedAt: 2000-01-23T04:56:07.000+00:00
          flowType: SupplierInvoice
      properties:
        limit:
          default: 25
          description: "Pagination, Maximum number of results that may be returned"
          maximum: 100
          type: integer
        nextCursor:
          allOf:
          - $ref: '#/components/schemas/Cursor'
          description: |
            Pagination management:
            - If present, says where to start for next page, set nextCursor as the cursor in the next request
            - If omitted, says that pagination is finished
        filters:
          $ref: '#/components/schemas/SearchFlowFilters'
        results:
          items:
            $ref: '#/components/schemas/Flow'
          type: array
      type: object
    WebhookParams:
      example:
        flowTypes:
        - SupplierInvoice
        - SupplierInvoice
        flowDirection: Out
        ackStatus: Pending
        callbackUrl: https://openapi-generator.tech
      properties:
        callbackUrl:
          format: uri
          type: string
        flowTypes:
          items:
            $ref: '#/components/schemas/FlowType'
          type: array
        flowDirection:
          $ref: '#/components/schemas/FlowDirection'
        ackStatus:
          $ref: '#/components/schemas/FlowAckStatus'
      required:
      - callbackUrl
      type: object
    WebhookId:
      format: uuid
      type: string
    WebhookIdParam:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        webhookId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        signingKey: signingKey
      properties:
        webhookId:
          format: uuid
          type: string
        signingKey:
          format: byte
          type: string
        createdAt:
          format: date-time
          type: string
      type: object
    Webhook:
      allOf:
      - $ref: '#/components/schemas/WebhookIdParam'
      - $ref: '#/components/schemas/WebhookParams'
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        webhookId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        flowTypes:
        - SupplierInvoice
        - SupplierInvoice
        flowDirection: Out
        ackStatus: Pending
        signingKey: signingKey
        callbackUrl: https://openapi-generator.tech
    Error:
      description: Error code
      example:
        instance: /chemin/url-de-reference#instance-du-contexte
        errorMessage: Invalid request format
        errorCode: MISSING_REQUIRED_FIELD
        details: Error detailed description
        type: /path/reference-url
      properties:
        errorCode:
          description: Short numerical or alphanumerical code that identifies precisely
            a unique error.
          example: MISSING_REQUIRED_FIELD
          type: string
        errorMessage:
          description: "Contains information on the error. Not intended to be displayed\
            \ to an end user. For security reasons, a tradeoff between clarity & security\
            \ shall be found."
          example: Invalid request format
          type: string
        type:
          default: about:blank
          example: /path/reference-url
          format: uri-reference
          type: string
        details:
          example: Error detailed description
          type: string
        instance:
          example: /chemin/url-de-reference#instance-du-contexte
          format: uri-reference
          type: string
      required:
      - errorCode
      type: object
    createFlow_request:
      properties:
        flowInfo:
          $ref: '#/components/schemas/FlowInfo'
        file:
          description: "Flow file: Max size = 100 MB"
          format: binary
          type: string
      required:
      - file
      - flowInfo
      type: object
    listWebhooks_200_response:
      example:
        webhooks:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          webhookId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          flowTypes:
          - SupplierInvoice
          - SupplierInvoice
          flowDirection: Out
          ackStatus: Pending
          signingKey: signingKey
          callbackUrl: https://openapi-generator.tech
        - createdAt: 2000-01-23T04:56:07.000+00:00
          webhookId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          flowTypes:
          - SupplierInvoice
          - SupplierInvoice
          flowDirection: Out
          ackStatus: Pending
          signingKey: signingKey
          callbackUrl: https://openapi-generator.tech
        count: 0
      properties:
        count:
          type: integer
        webhooks:
          items:
            $ref: '#/components/schemas/Webhook'
          type: array
      required:
      - count
      - webhookIds
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
    OAuth2:
      description: Implements only OAuth2 Client Credentials workflow requiring a
        client id/secret pair
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: "https://auth.company.com/auth-service/{custId}/token"
      type: oauth2

